### ISSUE TITLE
Setup handbook repository

### ISSUE THREAD

**Issue by jeffmaher** [Bloom-Works/handbook#1]
# Stories

As a guides writer, I want to be able to easily write, edit, and collaborate on guide content so that I can share what I've learned.

As a guides developer, I want my repo to be setup for users to easily find files, clear change management workflows, preview environments, and automatic deployments so that I can save time on manual tasks and enable users to work without deep technical knowledge.

# Done When

- [x] Developer setup instructions are documented
- [x] Protected branches configured
- [x] Blocking automated code style tests are run in PRs
- [ ] ~Idempotent builds configured (i.e. dependencies are fixed)~

**Comment by jeffmaher** [comment]
Open question ( @dottiebobottie , @danielhonker , @coreycaitlin ): Are the sections stable enough to include the last checklist item (migrate content) as acceptance criteria for this ticket?

**Comment by coreycaitlin** [comment]
Moved last item to #144
