### ISSUE TITLE
The banner is ENORMOUS

### ISSUE THREAD

**Issue by coreycaitlin** [Bloom-Works/handbook#110]
# Comment/suggestion
The giant green banner is extremely giant, which means that on wider screens/windows, it takes up > 50% of the content area.

# Context and user stories
People are likely to be using the handbook to look for specific information they need, so the layout should be optimized for quick scanning or skimming. The big green banner makes sense for a more immersive, linear experience, but I think we should consider shrinking the header space for the Handbook specifically. (This may be less of an issue on mobile, given different screen dimensions.)

As a Bloom employee, I want to be able to quickly skim the nav and first few paragraphs of the page, so that I can bounce to a different page if this one doesn't have what I need. (Or skip to the section I want.)

**Comment by jeffmaher** [comment]
Totally agree. I think the original intent was to make room for an image, but in hindsight we don't really need this. Let's def change it.
