### ISSUE TITLE
Publish v1 of handbook and deprecate old handbook

### ISSUE THREAD

**Issue by coreycaitlin** [Bloom-Works/handbook#111]
# Context 
tbd

# This issue is dependent on...
- #73 
- #108 
- #107 
- #31 

# Timeline
By BloomCon (9/21)

Done When
- [x] We have decided on a URL
- [x] We have a plan for pulling the old handbook offline

**Comment by coreycaitlin** [comment]
URL options:

- http://handbook.bloomworks.digital - likely to work more reliably with relative links as currently referenced in templates; potentially easier
- http://bloomworks.digital/handbook/ - would need to fix some internal links

**Comment by danielhonker** [comment]
Renamed the issue to include the remaining work -- pulling down the old handbook.

**Comment by coreycaitlin** [comment]
This is done! 🎉
