### ISSUE TITLE
Clean up our issues, tags, and backlog to use in ongoing backlog management

### ISSUE THREAD

**Issue by danielhonker** [Bloom-Works/handbook#132]
Clean up the issues. Review the issues we created before the initial publication/release, close any that are done at this point. 

Review the backlog and update the columns to be more appropriate for ongoing iteration (vs initial publication, which was more waterfall-style, milestone-based). 

Clean up the tags
- Bug - broken link, something doesn't work
- Wording update
- Remove tags that were intended only for the initial publication

# Stories

As a Handbook team member, I want a backlog that allows me to organize issues by new (ungroomed), groomed, ready to start, urgent/asap... so that I can track work and prioritize or take on issues according to priorities we've agreed to. 

As a Handbook team member, I want the issues to reflect what we're actually working on, so that I can know what I need to work on. 

As a contributor or Handbook team member, I want to use issue tags that reflect our workflow post-v1 so that I can tag issues in a way that will be helpful for managing our workflow. 

# Done When

- [x] tags are updated 
- [x] tags approved by @coreycaitlin and @dottiebobottie 
- [x] issue templates are updated  // https://github.com/bloom-works/handbook/pull/135
- [x] issue templates approved by @coreycaitlin and @dottiebobottie 
- [x] issues that were related only to the initial publication, and where work is finished, are closed
- [x] backlog columns and workflow are updated 
- [x] backlog columns and workflow are approved by @coreycaitlin and @dottiebobottie

**Comment by danielhonker** [comment]
- Updated [backlog columns](https://github.com/orgs/bloom-works/projects/7/views/2) to include 'Needs grooming' and 'Groomed and ready'. 
- Suggest use tags rather than backlog columns to indicate priority level. Created new 'priority-critical' tag. 
- Closed #90 
- Needs discussion:
  - #111 
  - #34 
  - #67

**Comment by coreycaitlin** [comment]
Calling this done!
