### ISSUE TITLE
Add content: Add Bloom glossary

### ISSUE THREAD

**Issue by dottiebobottie** [Bloom-Works/handbook#133]
# Description
The Bloom glossary is a great resource for all the acronyms and is kinda off on it's own
# Stories
_One or more statements that describe the beneficiary and reason for this to be implemented. Example:_

> As a Bloom employee, I want a quick resource to find out what acronyms are/add them, because/so that I can understand what people are talking about when I see a TLA IDKA (three letter acronym I don't know about)

# Draft content
[_Link to any draft content that exists and should be referenced_
](https://docs.google.com/document/d/1mjXnPREXNWv3_dQxwwmD9tHBQCG6Zrj2HuLTa6GLdNA/edit#heading=h.o0nvkdv8zref)
# Notes
Helpful notes that will help understand the intention of the ticket, things that have been tried, past brainstorms, or other helpful information.

**Comment by coreycaitlin** [comment]
Next steps: Find a spot for this link!

**Comment by coreycaitlin** [comment]
Seems like this document will be hard to maintain as projects come and go — closing this issue.
