### ISSUE TITLE
Smoother navigation through sections

### ISSUE THREAD

**Issue by aartikelapure** [Bloom-Works/handbook#138]
As a user, I want to click next at the bottom of each section instead of having to scroll to the top and select from the menu every time. [Captured in #130]

If I am looking at the menu, I would like it to tell me which section I am currently on, so I know which section to click on next. [Captured in #131]

**Comment by danielhonker** [comment]
A couple related nav issues: 
- #131 
- #109 
- #130

**Comment by coreycaitlin** [comment]
Thanks for the suggestion @aartikelapure! We've got the parts of this captured in a couple places now, so I'm closing this issue.
