### ISSUE TITLE
Missing link for remote work stipend

### ISSUE THREAD

**Issue by aartikelapure** [Bloom-Works/handbook#139]
There is a missing link at the end of the section "[Remote work stipend](https://bloom-handbook.netlify.app/sections/pay-and-benefits/#remote-work-stipend)" 

"Need suggestions on how to use your stipend? Bloomers have captured some recommendations in this doc: MISSING LINK"

**Comment by coreycaitlin** [comment]
Related to #143

**Comment by coreycaitlin** [comment]
This has been fixed!
