### ISSUE TITLE
Add a DEI statement to the About Bloom section?

### ISSUE THREAD

**Issue by dottiebobottie** [Bloom-Works/handbook#141]
We currently have a diversity statement on our Jobs page, but I feel like having it in our handbook will be a good addition. 
https://docs.google.com/document/d/1MQuHagd8QqFct3JVgGuhEufNBHpwg0slqKV_YrmGyzo/edit#heading=h.wjc06bsbp482

**Comment by coreycaitlin** [comment]
The content already exists, and should also exist in the Handbook! 🚢

**Comment by dottiebobottie** [comment]
Update in About section

**Comment by danielhonker** [comment]
In #147
