### ISSUE TITLE
Expand ProDev messaging

### ISSUE THREAD

**Issue by dottiebobottie** [Bloom-Works/handbook#143]

**Comment by dottiebobottie** [comment]
**Proposed text:**
You’ll have access to your professional development (ProDev) budget after your 4 month calibration meeting with your manager. For spending amounts over USD $50, you'll need to get approval in advance by sending an email to your manager and People Ops. Include a brief explanation of how the expense is relevant to your role and professional development. 


This budget can be used for a number of things:

- Online or in-person courses
- Testing fees & renewal costs associated with professional certifications
- Leadership coaching and mentorship
- Bloom has a coach we use, but you can find one that works for you
- Conferences (including flight and hotel where applicable)
- Some conferences offer group discounts, so let your coworkers/[DSC](https://bloom-handbook.netlify.app/sections/about-bloom/#our-community-%26-field)/[DWOSBA](https://bloom-handbook.netlify.app/sections/about-bloom/#our-community-%26-field) colleagues know!
- Books
- Other costs incurred becoming a smarter, more awesome version of you

Items not covered in ProDev:

- Software for day-to-day or personal use
- Tuition reimbursement
- Conferences/events not relevant to your professional development
- Bloom events that are related to professional development or recruiting

These are not exhaustive lists, so it is important to talk your manager about how to best use your stipend.

If you have professional development needs that go beyond your annual budget, have a conversation with your manager to see if there is a way to . ProDev funds are not retroactively approved, so make sure you communicate your plans with your manager before making any commitments. 


If you need ideas on how to spend your ProDev stipend, [this list](https://docs.google.com/document/d/17qkJeBXQL3PsmHNJaGdtkzyS4sfvV4QDi2aGkGwVfCk/edit?usp=sharing) is being populated with opportunities Bloomers recommend. 

Professional development funds do not carry over at the end of the calendar year, so get busy learning something! 


If you have any questions, reach out to your manager or People Ops.

**Comment by danielhonker** [comment]
Love the list of pro dev recs!

**Comment by coreycaitlin** [comment]
No policy change here, just a bit more guidance and detail about how to use.

**Comment by danielhonker** [comment]
In #147
