### ISSUE TITLE
Add acknowledgement links to handbook

### ISSUE THREAD

**Issue by dottiebobottie** [Bloom-Works/handbook#150]
# Description
_Briefly describe the content you want to see updated or created_

# Stories
As a person acknowledging the contents of the handbook, I want to easily find and sign documentation
> As a {{user or stakeholder}}, I want {{what}}, because/so that {{why}}

# Draft content
[Link to the acknowledgments in Google Drive
](https://drive.google.com/drive/u/0/folders/1dbGv6qETdNMnB-YeJySAEPSUP7EchqYD)
# Notes
I previously housed these in Gusto, but the way Gusto is set up, these would need to be signed while signing up for payroll and is a blocker. This is not a permanent solution because it would be nice to have e-sign, but this will do.

**Comment by coreycaitlin** [comment]
Currently @dottiebobottie is emailing these acknowledgments to folks, which seems to be working okay. Also, the agreements might be different in Gusto vs. Remote.

Decision: we will close this issue and keep the non-Handbook-website version of this process!
