### ISSUE TITLE
Add content about 2FA and profiles 

### ISSUE THREAD

**Issue by coreycaitlin** [Bloom-Works/handbook#162]
# Description
We have some new policies re security

# Stories

> As a Bloom employee, I want to know what to expect and how to set up my computer, because/so that I can follow the rules and not be confused.

# Draft content
No draft content yet.

**Comment by coreycaitlin** [comment]
Blocking question: what email address to use for contact info re security?

Possible solution from @jeffmaher — use security@bloomworks.digital Google Group to include needed contacts.
Dottie actively working on language for this.

**Comment by ekadernauth** [comment]
I [drafted language](https://docs.google.com/document/d/1ciMpQ2LSPynpH1pBHPH1DO0IGytXgzcBhZZMPb6vjKc/edit#heading=h.sy7gcpwuosdg) to for the update, but can use support on the appropriate section for this.

**Comment by coreycaitlin** [comment]
Edited and made some calls about where each graf should go. @dottiebobottie has staged in #164
