### ISSUE TITLE
First week set-up - Trello link

### ISSUE THREAD

**Issue by ekadernauth** [Bloom-Works/handbook#163]
Section: "[Get to know your coworkers](https://bloom-handbook.netlify.app/sections/things-to-set-up/#get-to-know-your-coworkers)"

Issue: Trello link is outdated. I have been migrating the Bloomer Trello board to Airtable. I created a [form](https://airtable.com/appLOyJgKy6s8mbc7/shr2XiwRR3P75ehln) that Bloomers can submit their responses that will generate a [card view interface ](https://airtable.com/appLOyJgKy6s8mbc7/pagessaOdl3c30mxl). The form link is public, however the interface link may need more thought on how to publish without requiring an Airtable account.

**Comment by coreycaitlin** [comment]
Closing in favor #170
