### ISSUE TITLE
Implement governance plan in code and content

### ISSUE THREAD

**Issue by jeffmaher** [Bloom-Works/handbook#34]
# Stories

As a Bloom employee, I want to learn how I can suggest updates to the handbook and submit questions to clarify policies and practices -- and understand how Bloom leadership will review my submission -- so that I can contribute to the handbook and participate in its iteration. 

As a Bloom manager or ops team member, I want to give instructions on how Bloom employees can suggest updates, contribute content, and ask questions about the handbook -- and share information on how those requests will be reviewed -- so that we make this a living document that grows and evolves with our team. 

As an ops team member, I want specific sections to automatically request reviews from the relevant reviewing group, so that I don't have to do this coordination manually and save time. Additionally, this will help signal to managers and ops team members when something is awaiting their review.

As an ops team member or tech ops person, I want to intake suggestions, drafts of new or updated content, and questions about the handbook, as issues in this repo, so that we can manage, prioritize, and process tickets and maintain a source of truth for updating the handbook. 

# Other notes
[Revamp draft doc](https://docs.google.com/document/d/1IWmW3pYjCnryU8rEQeenjtBX7VtvQeL-4AfVJHcyPXc/edit#heading=h.goluptexhq37
) -- for drafting handbook content on how to contribute 

# Done when
- [x] Governance plan from #66 is documented in `CONTRIBUTING.md`, and linked from `README.md`
- [x] Reviewer groups are setup within GitHub
- [ ] `CODEOWNERS` policy is in place to automatically assign and require reviews
- [ ] Issue template for intaking contributions exists and is linked to from `CONTRIBUTING.md`

**Comment by danielhonker** [comment]
@jeffmaher I made some updates to the readme in [this branch](README.md). Ok to call this closed after merge, or were you looking additional documentation on our approach?

**Comment by jeffmaher** [comment]
@danielhonker : Might be good to keep in the backlog. Apologies for never adding a description. I think the intent here was to add documentation for how someone at Bloom would add or edit something to the handbook.

**Comment by danielhonker** [comment]
Refined this issue to focus on implementing the governance plan from #66

**Comment by coreycaitlin** [comment]
Note from a comment in the draft governance plan doc:

> Can turn these groups into Github subteams for handbook review. 

> Can then tag gh pages as living with one of these groups. That will associate the page with the appropriate review group. 

> Could create a triage group that's just Dottie, to triage new pages to the right review group. Will train on how to assign a page to a group.

**Comment by danielhonker** [comment]
Keeping this open. `CODEOWNERS.md` automation still to do. 

Related to #128

**Comment by ghost** [comment]
Setup [review groups](https://github.com/orgs/bloom-works/teams/handbook/teams) based on [the governamce plan](https://github.com/orgs/bloom-works/teams/handbook/teams). Only remaining part is that Lara Kohl isn't in our GitHub Org, so I'll add her into the `Handbook- Misc Changes` group after I get her user ID.

Next step is to configure the repository to require reviews from the correct group based on the file being modified.
