### ISSUE TITLE
Add content: Company policies > Benefits for Full Time Employees (FTEs)

### ISSUE THREAD

**Issue by danielhonker** [Bloom-Works/handbook#45]
## Where to find the content
https://docs.google.com/document/d/1IWmW3pYjCnryU8rEQeenjtBX7VtvQeL-4AfVJHcyPXc/edit#heading=h.8mn0smcgrrgh

## Where the content will go
Company policies > Benefits for Full Time Employees (FTEs)

## Person responsible for this content
@dottiebobottie 

## Approver
_who will approve it or already did // we'll also track this via this github workflow_

**Comment by dottiebobottie** [comment]
I will be responsible for this content
