### ISSUE TITLE
Add e-sign for mandatory forms

### ISSUE THREAD

**Issue by danielhonker** [Bloom-Works/handbook#65]
## Where to find the content
https://docs.google.com/document/d/1IWmW3pYjCnryU8rEQeenjtBX7VtvQeL-4AfVJHcyPXc/edit#heading=h.9w5xx4sj2npd

Add option to e-sign the docs:
[Anti-harassment Policy](https://drive.google.com/file/d/1K1XtOvo4xAivqDSoea0KoxO_DTF1SjVe/view)
[Confidentiality, non-solicitation, and non-competition agreement](https://drive.google.com/file/d/1OqNTdw9T1ubigQ6yFrUIgTsW7xSMt6Nk/view)
[Acknowledgement and receipt of Bloom Handbook](https://drive.google.com/file/d/1nVa_tenuSdpQhDZMOg1hsTMcsxz34xrx/view)

## Where the content will go
Should this go as a page at the end of the handbook, or as part of a checklist? 

## Person responsible for this content
@dottiebobottie 

## Approver
TBD

**Comment by danielhonker** [comment]
@jeffmaher is checking to see if we have e-sig tool we could use.

**Comment by jeffmaher** [comment]
@smforelle would be a good person to ping for the info.

**Comment by coreycaitlin** [comment]
Per @dottiebobottie: Gusto will handle this! And we'll handle non-Gusto users via email.
