### ISSUE TITLE
Create governance plan for reviews and contributions

### ISSUE THREAD

**Issue by danielhonker** [Bloom-Works/handbook#66]
# Stories

As a Bloom manager or ops team member, I only want the deployed copy of the handbook to have approved changes so that folks can't push policy and norm changes without discussion.

As a Bloom manager or ops team member, I want Bloomers to be able to contribute changes to the handbook and have a mechanism to accept/decline/modify those contributions, so that everyone within Bloom is empowered to participate. 

As an ops team member, I want specific sections to automatically request reviews from the relevant reviewing group, so that I don't have to do this coordination manually and save time. Additionally, this will help signal to managers and ops team members when something is awaiting their review.

# Other Notes

Once a section is drafted/updated, it will go to a director for review and approval. At that point, the assignee will switch from the drafter to the reviewer. We need to decide who should review what parts of the handbook. 

It would be nice to automate the review handoff and change of assignee, based on rules about who reviews which parts of the handbook. 

# Done When

- [x] We have drafted a governance plan that describes: 
  - Who reviews and how these are done
  -  How Bloomers can contribute
  - How we know if the approach is successful, and what to change
  - Timeframe for a pilot 
- [x] Every section has 2 or more reviewers
- [x] Bloom leadership has reviewed and approved the governance plan

Related issue #34 is to implement this governance in code and content

**Comment by danielhonker** [comment]
Github owners - enforces change management process. 

For the initial build, list who should approve each section in the google doc. Once we have agreement, we can tag that person when the content is ready for review. 

Who approves what? 
- Anything with financial implication - Lauren, Emdash, Sofia
- People process, company rituals  - Dottie
- Most everything else - by directors and company leadership

Process
- Async workflow is ideal, but need some time to build the process. May need reminders in meetings for the time being:
- Biweekly directors meeting - @jeffmaher can remind ppl of reviews
- Dottie/Sofia weekly meeting 
- Weekly staffing review - not this topic, but can remind 

Next steps
- [x] @jeffmaher will raise question of who reviews what content in 7/18 meeting
- [ ] @danielhonker document review process in this repo

**Comment by danielhonker** [comment]
@jeffmaher tagging you on this for the next step - to raise question of who reviews in leadership meeting.

**Comment by danielhonker** [comment]
Approvers based on sections:

- **About this handbook**: Dottie, Emdash
- **About Bloom**: Dottie, Emdash 
- **Code of Conduct**: Dottie, Emdash, Sofia, Lauren 
- **Company policies for salaried employees**: Dottie, Emdash, Sofia, Lauren
  - **Expenses and reimbursement procedures**: Dottie, Emdash, Sofia, Lauren
  - **Time off**: Dottie, Emdash, Sofia, Lauren
  - **Travel and relocations**: Dottie, Emdash, Sofia
  - **Benefits for Full Time Employees (FTEs)**: `TBD`
- **Norms and Best Practices**: `TBD`
- **Career growth, professional development, and competencies**: `TBD`
- **Tools and getting set up**: `TBD`
- **Digital security**: `TBD`
- **Business continuity**: `TBD`
- **Leaving Bloom**: Dottie, Sofia
- **Working partners and coalitions**: Dottie
- **Information for contractors**: Sofia
  - **Offboarding**: Sofia, Dottie

Lingering issues:
- Who to assign when multiple reviewers
- Document this in README -- #62

**Comment by danielhonker** [comment]
This issue overlaps with #34 . @danielhonker revisit these tickets in light of notes ⬇  

Notes from @coreycaitlin : 
- May want to note some metadata. 
- 'This section is legalese.' 
- Note the reviewers for each section. 
- Don't ever want company owners surprised by something that's in the handbook. Need to design this process to serve this goal. Slack update? Manual flag? Notification? 

Move out implementation and documentation into #34 ? 

Draft handbook governance plan.
- Document the process we'll run for 6 months and the indicators we'll look for. 
- Need a policy on who merges updates.

**Comment by danielhonker** [comment]
Refined this issue to focus on creating the draft governance plan. Closely linked to #34 which is about implementing governance in code and content.

**Comment by coreycaitlin** [comment]
Calling this done! Further steps will go in #34
