### ISSUE TITLE
Complete handbook organization and draft content

### ISSUE THREAD

**Issue by danielhonker** [Bloom-Works/handbook#71]
Complete the handbook draft content in advance of: #86 

# Stories
As a Bloom manager or ops team member, I need to see an agreed-to structure for the initial handbook content so that I can draft and organize content in the right places. 

As a Bloom leader or ops team member, I need to review a complete draft of the handbook so that I can provide feedback and move the content forward to publication. 

As a Bloom tech ops person, I need to have an agreed-to structure for the initial handbook publication so that I can deploy content in the right place. 

# This issue is dependent on...
Just time 😄 

# This issue is a dependency/blocker for...
#87 

# Timeline

Targeting to have organization set by Aug 11

# Where we're doing work

[Table of contents in revamp drafting doc is here](https://docs.google.com/document/d/1IWmW3pYjCnryU8rEQeenjtBX7VtvQeL-4AfVJHcyPXc/edit#heading=h.ngm9vnjyr03r)

# Done when

- [x] We have agreed-to documentation of which sections get their own page, what the page titles are, and which content is included as a section within a page.  
- [x] The headings in the draft revamp doc reflect the agreed-to content structure ⬆ 
- [x] We have agreement on which sections will be published as "in progress"
- [x] We have agreement on which pages have restricted access (maybe we have another issue for locked access to some content?)
- [x] Content is drafted in the google doc
- [x] Google doc is shared for ops and owner review #87

**Comment by danielhonker** [comment]
Tagging @coreycaitlin and @dottiebobottie since y'all are already working on this.

**Comment by danielhonker** [comment]
@danielhonker will redo the issues to be one issue : one section. 

Some big sections might get caught up in reviews. Don't want to prevent the section from moving forward, so take note of if this happens, and consider breaking the content into more bite-sized chunks. 

We'll start opening pull requests to migrate content into markdown in about two weeks -- ~Aug 15.

**Comment by danielhonker** [comment]
As of today, 4 sections still 🚧   Making progress! 🚀

**Comment by coreycaitlin** [comment]
This is complete! We have a full draft 🎉 

- Pages are denoted with a 📄 icon (in the doc), with a few remaining questions about section landing pages, which we'll figure out as we get to know the guides template (if needed, we can add some intro content to each large section "landing page."
- I don't think any sections need to be published as "in progress", but we've identified a number of "v2" sections
- All pages with restricted access will live in GDocs, and are not currently part of the main handbook draft
- We're ready for #87
