### ISSUE TITLE
Build review workflow

### ISSUE THREAD

**Issue by danielhonker** [Bloom-Works/handbook#72]
We are manually assigning reviewers of content for the initial publication of the handbook -- based on #66 . 

After the initial release and once we're managing content and updates in github, we need will want to automate how we queue content issues for review by the right group. This will eliminate the need to manually assign reviewers to each issue, and help us keep issues from languishing without review. 

Assumptions:
- The reviewer(s) for a given piece of content will be determined by the section that content falls under. Reviewers by section are listed in #66 

Need to clarify:
- Who reviews if a section has multiple reviewers?
- How to automate the review assignment -- by tag in the markdown file?

**Comment by jeffmaher** [comment]
Seems like we're making fast enough progress to just get the process implemented in #66. Will close this ticket, but we can revive if we can't get the automated process in place by Fri, July 28.
