### ISSUE TITLE
Migrate content

### ISSUE THREAD

**Issue by danielhonker** [Bloom-Works/handbook#73]
# Context
Once content is drafted, reviewed, and approved, we will migrate content from google docs into markdown files in this repo. We will then review, merge, and publish the handbook content.

# This issue is dependent on...
#71 
#87  
#86 
#108 
#107 

# This issue is a dependency/blocker for...
#83 

# Timeline
Target Aug 28 to start migrating. Finish migration by Sep 1. Complete merges by Sep 17. 

# Where we're doing work
Migrating content from [handbook draft doc](https://docs.google.com/document/d/1IWmW3pYjCnryU8rEQeenjtBX7VtvQeL-4AfVJHcyPXc/edit#heading=h.a5s6c9czkuor) into markdown files in this repo. 

# Done When

- [x] Migrators learn how to migrate content into github
- [x] We have a checklist for migrating content into github
- [x] Content for each handbook section has been moved into markdown files
- [x] ~Pull requests are opened for new markdown files~ Corey accidentally merged these straight into main, but won't do that again
- [x] We have created new gh issues for any comments that we cannot resolve before publishing
- [x] All pull requests merged that include content for the first publication

**Comment by danielhonker** [comment]
@danielhonker to merge this issue with #88 

Host a training session on markdown with @jeffmaher @dottiebobottie. @danielhonker will schedule

Make sure reviewers have some time carved out to review and hit approve. Will likely be quick and light since they will have just reviewed the doc in google.

**Comment by danielhonker** [comment]
# Notes on migrating and contributing

## 1. Contributing on github
- Branches - copy of the whole repo that we will change
- Commits - specific changes on the branch
- Pull request - ticket for a change to the main branch. Want to group a lot of commits into one PR for ease of review and approval. 
- Merging - applying the changes from the new branch to the main branch

## 2. Markdown
- https://markdown.land/markdown-cheat-sheet 
- Use text editor or github web interface
- Can change github URL from .com to .dev to bring up a web-based text editor. 
- Use internal links (i.e., not full-length URLs) so that previews render correctly 

## 3. Guide template
- Going for a chapter structure, but built on a flat, sequential -oriented platform. Building the chapter-based navigation now (and hope to have it built by BloomCon), but for the time being, we will migrate H2s as sections. 

## 4.

**Comment by coreycaitlin** [comment]
Added a couple new issues to the dependencies list above — we may want to split this issue so that "publication" gets its own issue!
