### ISSUE TITLE
Team comment period

### ISSUE THREAD

**Issue by danielhonker** [Bloom-Works/handbook#83]
# Context
We will release the handbook for comment at the offsite. Team comment period will be time-boxed for Bloomers to review, comment, ask questions. We will intake submissions using github issues and offer guidance to team members not yet familiar with github. 

# Stories

As a handbook core team member, I want to invite comments and questions on the handbook so that I can address issues that need clarification, and . 

As a Bloom employee, I want to read and comment on the handbook before publication so that I can provide feedback and help shape a resource intended for the whole team. 

As a handbook core team member, I need to invite all Bloomers to join and learn github so that I can intake contributions and manage discussions openly and in one place (i.e., github).

As a Bloom employee, I need to join the bloomworks github org and learn how to submit issues so that I can contribute to the handbook and follow discussions on updates.

# This issue is dependent on...
#88 

# This issue is a dependency/blocker for...

# Timeline
Release for team comment at BloomCon, Sept 20-22. 

10 days for team comment period. Most ppl will take 30-60 min to review. Want to make sure ppl can allot enough time to review and comment. 

# Where we're doing work
Issues and files in this repo

# Done When

- [x] Timelines and logistics for the public comment period are decided 
- [x] Call out what is net new in the handbook, so that Bloomers can skim
- [x] Issue template created to intake questions and comments from team review
- [x] Feedback form exists
- [x] Content exists to invite feedback and tell people how to share feedback and questions
- [x] We invited Bloomers to review the draft, with instructions and guidance on github
- [x] Window for comment closes (` X ` days)
- [ ] We have reviewed issues submitted and decided how we will prioritize them (#34 )

**Comment by danielhonker** [comment]
Will announce at the offsite. Can share the handbook with everyone when we get back. 

Give ppl a few options for sharing feedback (for the initial release and for long-term feedback):
- Talk to your manager
- Handbook slack channel -- in long-term, we could automate slack messages into github
- Feedback form (anon or not?) -- this feels like the short-term option. 
- Github issue or pull request

@dottiebobottie to create content on the comment period, how to give feedback.

**Comment by coreycaitlin** [comment]
URL for review will be: https://bloom-handbook.netlify.app/
