### ISSUE TITLE
Technical review/edit draft content

### ISSUE THREAD

**Issue by danielhonker** [Bloom-Works/handbook#86]
A technical review of the draft content before publication. 

# This issue is dependent on...
#71 

# This issue is a dependency/blocker for...
#73 

# Timeline

Finish by Aug 25

# Where we're doing work

https://docs.google.com/document/d/1IWmW3pYjCnryU8rEQeenjtBX7VtvQeL-4AfVJHcyPXc/edit#heading=h.a5s6c9czkuor 

# Done When

- [x] Editor has completed review and notifies the team that this is done

**Comment by danielhonker** [comment]
This will likely be Chelsea

**Comment by danielhonker** [comment]
@coreycaitlin will hand off to Chelsea today/tomorrow and ask her what kind of timing is possible.  Might be able to check-off sections as reviews are complete.

**Comment by coreycaitlin** [comment]
We are calling this copyedit done for now! Further copyediting can happen after the move to Markdown.
