### ISSUE TITLE
Ops and owner review of draft content (pre-publication)

### ISSUE THREAD

**Issue by danielhonker** [Bloom-Works/handbook#87]
# Context 
Ops team and Bloom leadership will review draft content and organization to ensure content is accurate and reflects values and policy decisions. 

# This issue is dependent on...
- #71 

# This issue is a dependency/blocker for...
- #86  

# Timeline
Target Aug 14 to start (when #71 is finished) and to complete by Aug 18

Where we're doing work
https://docs.google.com/document/d/1IWmW3pYjCnryU8rEQeenjtBX7VtvQeL-4AfVJHcyPXc/edit#heading=h.a5s6c9czkuor

Done When
- [ ] Ops team and Bloom leadership have finished review of content

**Comment by coreycaitlin** [comment]
We've added a checklist at the top of the doc, and @dottiebobottie is going to kick off review on Monday!

**Comment by danielhonker** [comment]
We will call this done by end of today. @dottiebobottie will review and resolve comments.
