### ISSUE TITLE
Dev work and resolve bugs for v1 release

### ISSUE THREAD

**Issue by danielhonker** [Bloom-Works/handbook#90]
This is an umbrella issue for dev work that needs to be done before v1 publication. We'll add specific dev issues -- especially those that we don't prioritize for v1 -- to the backlog. 

# Stories

As a Bloom manager or ops team member, I want to identify and resolve any technical issues or bugs with the platform before releasing handbook v1 so that the handbook works as expected for Bloomers. 

# Notes

# Done When

- [ ] platform issues/bugs are identified
- [ ] high priority platform issues/bugs are resolved (those critical for usability of v1)
- [x] tickets are added to the backlog for any issues/bugs not prioritized for v1

**Comment by danielhonker** [comment]
@jeffmaher - I added this umbrella issue for pre-publication dev work -- so we represent it in the [roadmap to v1](https://github.com/bloom-works/handbook/milestone/1). Qs for you... 
- Should we track individual issues in their own tickets (above some threshold of level of effort)?
- Do you need more definition on what kinds of dev work we would prioritize for v1?

**Comment by jeffmaher** [comment]
Status update:

- Updated Guides Template with some editing usability improvements. Will port those changes into Handbook today.
- Question: Should the nav show sections alphabetically or in a certain order? Answer: In a specific order.
- ^ This will need to be implemented, but shouldn't take too much time to put in place.

**Comment by danielhonker** [comment]
This was intended as a placeholder for technical issues for the initial launch. Issues that @jeffmaher mentioned above are either resolved or have their own issues now. So will close this as finished.
